### ISSUE TITLE
Determine which receptor arms to define clones by

### ISSUE THREAD

**Issue by Ngort** [zktuong/dandelion#299]
### Is your feature request related to a problem?

I'm working on a plasma cell pathology where we expect lots of the clones to have orphan VJ chains, and we'd like to use BCRseq to trace expanded clones. Unfortunately, Dandelion misses these because they don't have a functional BCR.

### Describe the solution you'd like

I'd like another parameter for define_clones, e.g. `receptor_arms="both"`, which can take values "VJ", "VDJ", "both" (the latter being the default).

I'm still trying to parse through the source of tl.define_clones but I think all the necessary parts should lie there. 

### Describe alternatives you've considered

I tried removing all VDJ chains from the Dandelion object but that fails. 
I tried clustering VJ chains from vdjx.data based on changeo_clone_id but they don't get clone_id assigned.

**Comment by zktuong** [comment]
Hi @Ngort, happy to support. 

Just want to clarify a few things:

I suppose you mean `tl.find_clones`? as define_clones just points to changeo's `DefineClones.py`

at the moment there is a single check at 
https://github.com/zktuong/dandelion/blob/159d7164b2b4873a3731b1ece2887a7630354152/dandelion/tools/_tools.py#L157
which basically would assert that the `.data` must contain VDJ, otherwise it would not perform the clustering.

I'm thinking i can can add an `ifelse` at the end of this entire chunk, and "duplicate" this section (as a separate function to reduce code bloat):

https://github.com/zktuong/dandelion/blob/159d7164b2b4873a3731b1ece2887a7630354152/dandelion/tools/_tools.py#L346-L590

So then i envisage that the `VJ` clone_id in this mode would just look like `NoVDJ_1_2_3` and vice versa in the `VDJ` mode, it would be `1_2_3_NoVJ` or something of the like.

Does this look like something you are after?

**Comment by Ngort** [comment]
I think that would fit!

**Comment by zktuong** [comment]
OK ! please bear with me as i try to implement it. Do you have a deadline you need this by?

**Comment by Ngort** [comment]
I'm trying to submit an abstract by Sunday, but obviously I don't mean to rush your generous work! Do you think there's a faster bootleg way for me to access the light chain clusters presumably generated during the tl.find_clones workflow?

**Comment by Ngort** [comment]
Sorry, I stand corrected. I did mean to point to `define_clones`, the wrapper of `DefineClones.py`, although the same statement can be made about `find_clones`. My understanding is that `DefineClones.py` simply aligns sequences of any locus, regardless of whether they're paired to each other in a barcoded cell, and `define_clones` creates the cell clusters (clone_id). Thus, I'd assume there's a way to use changeo's wrapper with just VJ data. Is this accurate?

**Comment by zktuong** [comment]
Ah i’m not sure… probably? If you change back to the previous release, the code based for define_clones is still there and you could try and run it.

Sorry as this code is implemented by the changeo people i can only offer limited assistance (don’t really know what it does)

**Comment by zktuong** [comment]
dandelion's way of definining clonotypes for orphan VJ/VDJ has been implemented. see #329
