### ISSUE TITLE
Question about vdj1 and vdj2 in dandelion network plots

### ISSUE THREAD

**Issue by wonwon03172** [zktuong/dandelion#448]
### Description of the issue

Hi,

I’m currently using dandelion for my research and have a question regarding the network visualization. When I generate a network plot, the axes are labeled vdj1 and vdj2. According to the tutorial page, it says:

"Although the X and Y axes (vdj1 and vdj2) are arbitrary, the mod_fr layout seems to produce more pronounced repulsion between clusters, so something to keep in mind for when trying to work with a lot of cells/clusters as it can lead to really pretty (or ugly) plots."

Could you clarify what vdj1 and vdj2 represent? Specifically:

1. What do these values signify?
2. How are they calculated?

I couldn’t find detailed information in the tutorial, so I’d appreciate any additional explanation or reference you could provide.

Thank you!

![image](https://github.com/user-attachments/assets/d1d51839-7c91-4974-be6a-e76f3f643408)

**Comment by zktuong** [comment]
hi @wonwon03172, 

the values don't mean anything other than x/y coordinates. the default layout is basically spring layout https://networkx.org/documentation/stable/reference/generated/networkx.drawing.layout.spring_layout.html

**Comment by wonwon03172** [comment]
Do the "values" only represent positions on the plot? 

The documentation mentions that the Levenshtein distance is used to construct the network. 

How is this related (or unrelated) to the dimensionality reduction process based on the Levenshtein distance metric?

**Comment by zktuong** [comment]
the levenshtein distances (between TCR/BCRs) are used in the edges (the lines between the dots) so that organises how the little sub-graphs are formed. However, for the rest of the graph, where the subgraphs are placed are random and the layout is just arbitrary.

This is unrelated to the dimensionality reduction process currently as the distance matrix is not a complete one. In the very initial iteration of dandelion at https://github.com/clatworthylab/dandelion/tree/legacy, it returns a full distance matrix and than be used for e.g. umap later - but the tool is extremely slow and i can't gotten round to trying to redo it. maybe one day.

**Comment by wonwon03172** [comment]
I understand it well now. 

Thank you!
